#! /bin/sh

PLAN9=/usr/lib/plan9

EDITOR=E
unset FCEDIT VISUAL

PAGER=nobs

font=$PLAN9/font/lucm/unicode.9.font

PS1=" ; "

# variables for rc(1).
home=$HOME
prompt=" ; "
user=$USER

export BROWSER EDITOR FCEDIT PAGER PLAN9 PS1 VISUAL font home prompt user

SHELL=`which rc` acme -f /mnt/font/Bitstream\ Vera\ Sans/10a/font -F /mnt/font/Bitstream\ Vera\ Sans\ Mono/10a/font &
# SHELL=`which rc` acme -f /mnt/font/Droid\ Sans/11a/font -F /mnt/font/Droid\ Sans\ Mono/11a/font &

# end
