# .bash_aliases

alias a='h a'
alias b='h b'

alias xf='tar xzf'
alias cf='tar czf'

alias h3='python -m http.server 8123'

alias r='R -q'
# alias r='tmux new-session -s r-session R -q'

alias tf='tail -f'


alias bye='sudo shutdown -h now'


# end
